GET http://localhost:3001/api/getStudents 
# this url can only be called from frontend
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2MWM5Yjk1NmExZjhlNGUzN2NkZmMzYTQiLCJyb2xlIjoidGVhY2hlciIsIm5hbWUiOiJzYW50b3NoIiwiaWF0IjoxNjQ0NDEyMDc0LCJleHAiOjE2NDQ0MjI4NzR9.t5ce_bAzi0yeU-3nIrOI9zLxNNGv9ZgU-B0yN4v4FFY 
###
POST  http://localhost:3001/api/createStudent
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2MWM5Yjk1NmExZjhlNGUzN2NkZmMzYTQiLCJyb2xlIjoidGVhY2hlciIsIm5hbWUiOiJzYW50b3NoIiwiaWF0IjoxNjQwNjEwMTM1LCJleHAiOjE2NDA2MTM3MzV9.eEwN1xHMTo4Ed-97flGdGcR79QsqEFI4oIJt-RhlagQ 

{
      "name":"anmol",
      "email":"anmol@gmail.com",
      "rollNumber":123,
      "class":"LKG"
}
###
POST  http://localhost:3001/api/auth/login
Content-Type: application/json

{
      "email":"anmol@gmail.com",
       "password":"12345678",
       "rollNumber":"123"
    
}

###
POST  http://localhost:3001/api/auth/refreshToken
Content-Type: application/json

{
      "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2MWI5NDdkN2ExYzQ2MTdhOTkxMjI0YTEiLCJyb2xlIjoidGVhY2hlciIsImlhdCI6MTY0MDI2NTE1OCwiZXhwIjoxNjcxODIyNzU4fQ.edSYZdWknh03z1h0UrZV4Rl5U-jWPzoLsivkPOD8zIk"
 }



###
DELETE http://localhost:3001/api/auth/logout
Content-Type: application/json

{
      "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2MWI5NDdkN2ExYzQ2MTdhOTkxMjI0YTEiLCJpYXQiOjE2NDAwNTAzNTYsImV4cCI6MTY3MTYwNzk1Nn0._UX3_qQ8FBIHYnJ5weHE51-FdQlJfGUe6mjBr_5kcgw"
     }



###

POST  http://localhost:3001/api/auth/registerTeacher
Content-Type: application/json

{
      "name":"santosh",
      "email":"santosh@gmail.com",
      "password":"12345678",
      "subject":"English",
      "classes":["UKG","LKG"]
      
       }

###

PATCH   http://localhost:3001/api/auth/registerStudent
Content-Type: application/json

{
      "email":"karuna@gmail.com",
      "rollNumber":"123",
      "password":"12345678"
      
       }



###

 GET http://localhost:3001/api/auth/registerStudent?_class=LKG
Content-Type: application/json

{
      "email":"anmol@gmail.com",
      "rollNumber":"456",
      "password":"12345678"
      
       }

###

 PATCH  http://localhost:3001/api/openAttendence/?_class=LKG
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2MWM5YmEwMGExZjhlNGUzN2NkZmMzYWIiLCJyb2xlIjoic3R1ZGVudCIsIm5hbWUiOiJhbm1vbCIsImlhdCI6MTY0NDQxODg0OSwiZXhwIjoxNjQ0NDI5NjQ5fQ._Q3ZfKPtqc6tKtPdFm1pwVNbSueI60Mn1TivM-sc_YY 




###

 PATCH  http://localhost:3001/api/present/?subject=Economics
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2MWM5YmEwMGExZjhlNGUzN2NkZmMzYWIiLCJyb2xlIjoic3R1ZGVudCIsIm5hbWUiOiJhbm1vbCIsImlhdCI6MTY0NDQxODc2OCwiZXhwIjoxNjQ0NDI5NTY4fQ.sK4Gz-sC3qvTXLPO7QF0ql9YnmoKuAdZKBEz_VFxQrA