GET http://localhost:3001/api/getStudents 
# this url can only be called from frontend
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2MWM5Yjk1NmExZjhlNGUzN2NkZmMzYTQiLCJyb2xlIjoidGVhY2hlciIsIm5hbWUiOiJzYW50b3NoIiwiaWF0IjoxNjQ0NDEyMDc0LCJleHAiOjE2NDQ0MjI4NzR9.t5ce_bAzi0yeU-3nIrOI9zLxNNGv9ZgU-B0yN4v4FFY 
###
POST  http://localhost:3001/api/createStudent
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2MWM4Njk4NmUzMDJkMjU4ZWQ1ZGZhYzIiLCJyb2xlIjoidGVhY2hlciIsIm5hbWUiOiJwcmFuYSIsImlhdCI6MTY0NDQ1NjUzMywiZXhwIjoxNjQ0NDY3MzMzfQ.VgrQizOu8uwQg1FVgKHQVup3Yc2cjdMpIps-lN4i0Go 


{
      "name":"deepjoy",
      "email":"deepjoy@gmail.com",
      "rollNumber":123,
      "class":"2"
}
###
POST  http://localhost:3001/api/auth/login
Content-Type: application/json
{
      "email":"anmol@gmail.com",
       "password":"12345678",
       "rollNumber":123
}

###
POST  http://localhost:3001/api/auth/refreshToken
Content-Type: application/json

{
      "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2MWI5NDdkN2ExYzQ2MTdhOTkxMjI0YTEiLCJyb2xlIjoidGVhY2hlciIsImlhdCI6MTY0MDI2NTE1OCwiZXhwIjoxNjcxODIyNzU4fQ.edSYZdWknh03z1h0UrZV4Rl5U-jWPzoLsivkPOD8zIk"
 }



###
DELETE http://localhost:3001/api/auth/logout
Content-Type: application/json

{
      "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2MWI5NDdkN2ExYzQ2MTdhOTkxMjI0YTEiLCJpYXQiOjE2NDAwNTAzNTYsImV4cCI6MTY3MTYwNzk1Nn0._UX3_qQ8FBIHYnJ5weHE51-FdQlJfGUe6mjBr_5kcgw"
     }



###

POST  http://localhost:3001/api/auth/registerTeacher
Content-Type: application/json

{
      "name":"santosh",
      "email":"santosh@gmail.com",
      "password":"12345678",
      "subject":"English",
      "classes":["UKG","LKG"]
      
       }

###

PATCH   http://localhost:3001/api/auth/registerStudent
Content-Type: application/json

{
      "email":"karuna@gmail.com",
      "rollNumber":"123",
      "password":"12345678"
      
       }



###

 GET http://localhost:3001/api/auth/registerStudent?_class=LKG
Content-Type: application/json

{
      "email":"anmol@gmail.com",
      "rollNumber":"456",
      "password":"12345678"
      
       }

###

 PATCH  http://localhost:3001/api/openAttendence/?_class=2
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2MWM4Njk4NmUzMDJkMjU4ZWQ1ZGZhYzIiLCJyb2xlIjoidGVhY2hlciIsIm5hbWUiOiJwcmFuYSIsImlhdCI6MTY0NDQ1NjUzMywiZXhwIjoxNjQ0NDY3MzMzfQ.VgrQizOu8uwQg1FVgKHQVup3Yc2cjdMpIps-lN4i0Go 

###
 PATCH  http://localhost:3001/api/closeAttendence/?_class=LKG
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2MWM5Yjk1NmExZjhlNGUzN2NkZmMzYTQiLCJyb2xlIjoidGVhY2hlciIsIm5hbWUiOiJzYW50b3NoIiwiaWF0IjoxNjQ0NDU2MzY3LCJleHAiOjE2NDQ0NjcxNjd9.Lmyp_lG4KvOiLhdZDzfhr_dgjVbHkGt2lRYM2yW7vtM 
###
 PATCH  http://localhost:3001/api/present/?subject=Economics
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2MWM5YmEwMGExZjhlNGUzN2NkZmMzYWIiLCJyb2xlIjoic3R1ZGVudCIsIm5hbWUiOiJhbm1vbCIsImlhdCI6MTY0NDQxODc2OCwiZXhwIjoxNjQ0NDI5NTY4fQ.sK4Gz-sC3qvTXLPO7QF0ql9YnmoKuAdZKBEz_VFxQrAeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI2MWM5YmEwMGExZjhlNGUzN2NkZmMzYWIiLCJyb2xlIjoic3R1ZGVudCIsIm5hbWUiOiJhbm1vbCIsImlhdCI6MTY0NDQxODk0NCwiZXhwIjoxNjQ0NDI5NzQ0fQ.XvdAsAbcdNbOpd6RENWwZgagRrrHIOWNmS_toCeT3RA